apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps_name
  labels:
    env: branch
    project: projectid
    cloud: huawei
spec:
  destination:
    namespace: namespace
    name: clustername
  project: projectid
  source:
    repoURL: git@gitssh.bluebird.id:argocd/kubernetes-cluster.git
    targetRevision: main
    path: branch/service
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
      allowEmpty: false